# Generated by Django 5.2 on 2025-04-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='published_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='default_author', max_length=100),
            preserve_default=False,
        ),
    ]
